[package]
name = "bitprim"
version = "0.1.0"
authors = ["nubis <nb@bitex.la>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
error-chain = "0.11.0"

[build-dependencies]
regex = "0.2"

[dev-dependencies]
pretty_assertions = "0.5.1"

[features]
default = ["bch", "v0_9_1"]
bch = []
btc = []
ltc = []
v0_9_0 = []
v0_9_1 = []
